name: GlobalShield
main: globalshield\GlobalShield
version: 1.1.0
api: [1.10.0, 2.0.0]
load: POSTWORLD
author: Gamecrafter
description: Shield all of your worlds from griefers!
website: https://github.com/Viperize/GlobalShield-PocketMine
permissions:
 globalshield:
  default: op
  children:
   globalshield.action:
    default: op
    children:
     globalshield.action.bypass:
      default: op
